### ISSUE TITLE
"Starting Simple" episode outdated link

### ISSUE THREAD

**Issue by SubhrajitPrusty** [hangtwenty/dive-into-machine-learning#114]
http://www.thetalkingmachines.com/blog/2015/4/23/starting-simple-and-machine-learning-in-meds link doesn't work anymore.

[This](http://www.thetalkingmachines.com/episodes/starting-simple-and-machine-learning-meds) may be the correct one.

**Comment by hangtwenty** [comment]
Thanks @SubhrajitPrusty and @xkcao!
