### ISSUE TITLE
Elements of Statistical Learning vs. Understanding Machine Learning?

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#29]
[_Elements of Statistical Learning_](http://statweb.stanford.edu/~tibs/ElemStatLearn/) and [_Understanding Machine Learning_](http://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/copy.html) are both free books, and frequently recommended as reference textbooks. As you continue towards expertise you can also go deep into these books.

Issue: need to add link to UML in guide. Also need to link to context/comparison if possible.

**Comment by hangtwenty** [comment]
[These comments on Hacker News](https://news.ycombinator.com/item?id=10589398) give good context for comparing _Elements of Statistical Learning_ (ESL) with _Understanding Machine Learning_ (UML).

HN user arbitrage314:

> I'm a math geek, but I'm also a mostly self-taught data scientist.
> "The Elements of Statistical Learning" (https://web.stanford.edu/~hastie/local.ftp/Springer/OLD/ESLI...) is far and away the best book I've seen.
> It took me hundreds of hours to get through it, but if you're looking to understand things at a pretty deep level, I'd say it's well-worth it.
> Even if you stop at chapter 3, you'll still know more than most people, and you'll have a great foundation.
> Hope this helps!
	
HN user reader5000, in reply:

> Having read significant chunks of both ESL and Understanding Machine Learning (albeit UML much more recently) I would argue that for many readers UML is superior.
> ESL pays short shrift to the computational complexity of learning whereas UML explicitly handles both statistical and computational complexity concerns. It doesnt matter how statistically pure your algorithm is if its running time scales exponentially with your data.
> All of UML's chapters are conceptually unified even when discussing different ML algorithms, with ESL being more of a grab-bag by chapter.
> Still, both high quality and free!

**Comment by hangtwenty** [comment]
[This quora thread](https://www.quora.com/How-do-I-learn-machine-learning-1/answer/Xavier-Amatriain) also gives context about where _Elements of Statistical Learning_ would fit in a self-taught Machine Learning curriculum.

**Comment by Le0nX** [comment]
thx, guys!

**Comment by hangtwenty** [comment]
Found these, adding to guide, but thought I would cc them here since I link to this issue from the guide at one point.

> * [Stanford CS 229 cheat sheets](https://stanford.edu/~shervine/teaching/cs-229/), available on the web and [as PDFs](https://github.com/afshinea/stanford-cs-229-machine-learning/tree/master/en)
>   * **[Probabilities and statistics refresher](https://stanford.edu/~shervine/teaching/cs-229/refresher-probabilities-statistics)**
>   * **[Linear algebra and calculus refresher](https://stanford.edu/~shervine/teaching/cs-229/refresher-algebra-calculus)**
>   * [Supervised learning cheat sheet](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-supervised-learning)
>   * [Unsupervised learning cheat sheet](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-unsupervised-learning)
>   * [Deep learning cheatsheet](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-deep-learning) [(more)](https://stanford.edu/~shervine/teaching/cs-230/)
>   * [Machine Learning tips and tricks cheat sheet](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-machine-learning-tips-and-tricks)
