### ISSUE TITLE
Video series about scikit-learn designed for machine learning beginners

### ISSUE THREAD

**Issue by justmarkham** [hangtwenty/dive-into-machine-learning#34]
Hello! I have a suggestion for the repo, and thought an issue might be the best place to post it.

I created a video series about scikit-learn, designed specifically for Python users with no background in machine learning or scikit-learn. I thought it might be useful for your readers. Here are the relevant links:

GitHub repo containing the notebooks - https://github.com/justmarkham/scikit-learn-videos
each notebook is related to a video - https://www.youtube.com/playlist?list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A
each notebook is also related to a blog post - http://blog.kaggle.com/author/kevin-markham/

If you'd like a quick overview of the series, it can be found here:
http://blog.kaggle.com/2015/04/08/new-video-series-introduction-to-machine-learning-with-scikit-learn/

As a side note, the first video in the series isn't really about scikit-learn, it's just an introduction to how machine learning "works". Thus, it could be worth a separate link in your repo:
https://www.youtube.com/watch?v=elojMnjn4kk&list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A&index=1

Anyway, I'm happy to answer any questions and appreciate your consideration!

**Comment by hangtwenty** [comment]
Great contribution, and yes this is the place to post it :wink: I'll check out the resources and think about the best place to put it!
