### ISSUE TITLE
Link to Julia Evans blogpost, "Machine Learning isn't just Kaggle competitions"

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#44]
[Machine Learning isn't just Kaggle competitions](http://jvns.ca/blog/2014/06/19/machine-learning-isnt-kaggle-competitions/)

**Comment by FleetAdmiral** [comment]
Hey , could i take this up?

**Comment by hangtwenty** [comment]
@FleetAdmiral Sure, it's a quickie really, just need to link it somewhere in [this section](https://github.com/hangtwenty/dive-into-machine-learning#towards-expertise). It can even just be a link, using existing text. Just haven't gotten around to reading and adding the link

**Comment by jlar0che** [comment]
7777777777777777777777777777777777777777777777777771`

**Comment by jlar0che** [comment]
Seems like this wasn't followed up on. I'll do it now and send a PR.

**Comment by hangtwenty** [comment]
Thanks @jlar0che !
