### ISSUE TITLE
Add link to book: Python Machine Learning

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#50]
[_Python Machine Learning_](https://github.com/rasbt/python-machine-learning-book)

(and a [blog post reflecting on the writing of this book](http://sebastianraschka.com/blog/2015/writing-pymle.html))

**Comment by FleetAdmiral** [comment]
Hey i'd like to take this up. Could you guide me as to what exactly im required to do?

**Comment by hangtwenty** [comment]
@FleetAdmiral I suppose this one is very vague ... just a memo! If you check it out and you find a spot to link, feel free to.
