### ISSUE TITLE
Need a section about Deep Learning intro/way-out/next-steps if people are interested ... from someone who knows what they are talking about !

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#52]
(braindump)

I've largely avoided having much deep learning links or neural nets links ... because it seems like it can be dangerous for beginners to jump ahead to those when they are not ready. I don't know enough about deep learning to really situate this beside just a couple links in a list ... let alone situate it in a sober, smart way :)

Recently, [this MIT book about Deep Learning](http://www.deeplearningbook.org/) has been published, and judging by reactions it seems like a worthwhile resource to link to. I still don't want "everything and the kitchen sink" but this would be a good "essential resource" on the subject. Or maybe an expert knows a better choice.

So. Might want a small subsection to link to these two things, with the appropriate one or two sentence caveat that these are advanced topics, refer back to the pyramid showing that algorithm is least important (for _many_ problems), etc etc. Maybe link to a Talking Machines episode too to give the appropriate context.

**Comment by gauthamzz** [comment]
shoudnt there be something like dive into deep learning then

**Comment by hangtwenty** [comment]
@gauthamzz Good question ;)

But that's just the thing ... I do _not_ think there should be a "dive in" style guide for that topic. It's not really one you can "dive into." You have to really Know What You're Doing. I don't want to feed into the bit of hype that's been happening, around deep learning and neural nets, that can be counter-productive for beginners ... it's like if I were to start talking about AWESOME COMPILER OPTIMIZATIONS! early on in an "intro to programming" book.

This guide's purpose is to get you productive and get you momentum in learning ML. It doesn't try to educate you on advanced subjects, just starts you on the path, with faith that you can find your way once you get these basics down (and links to help you navigate, now and for the next X months/years). I have faith, for the most part, that if someone gets competent and productive, good enough to be "professional" with ML, then they will find their way through advanced subjects ... including deep learning, neural nets, and so on.

So, instead of another guide or something, I would rather just have a link or two, for people to "bookmark for later" when they are ready to take this advanced step. This might require some "refactoring" though...

**Comment by hangtwenty** [comment]
alsooo http://karpathy.github.io/2015/05/21/rnn-effectiveness/

**Comment by hangtwenty** [comment]
[CS231n Convolutional Neural Networks for Visual Recognition](http://cs231n.github.io/)

**Comment by hangtwenty** [comment]
This section should probably be inserted after the "Big Data?" section. Titled,

> Deep Learning, Neural Networks, and ...

**Comment by hangtwenty** [comment]
[link to this funny joke probably](http://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/)

**Comment by hangtwenty** [comment]
putting the [buzz](https://backchannel.com/how-google-is-remaking-itself-as-a-machine-learning-first-company-ada63defcb70) [fizzbuzz](http://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/). I kid, I kid

**Comment by hangtwenty** [comment]
But seriously [here is a good introduction to link to, as it's consistent with the same style of our guide](http://ofir.io/How-to-Start-Learning-Deep-Learning/); would just make sense.
