### ISSUE TITLE
[Contributions Welcome!] Look into book about "Test-Driven Approach" to learning Machine Learning; add a note in the guide

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#63]
[Thoughtful Machine Learning with Python: A Test-Driven Approach 1st Edition
by Matthew Kirk](https://www.amazon.com/Thoughtful-Machine-Learning-Python-Test-Driven/dp/1491924136/). Looks very interesting. I want to look into the book and/or early reviews of it, and most likely find a place to link it in the guide.

**Comment by hangtwenty** [comment]
The note should go in "Assorted Opinions..." after "Ask for Peer Review."

**Comment by solisruj** [comment]
I saw an issue, and wanted to contribute if possible.

**Comment by hangtwenty** [comment]
@solisruj Sure. The issue is open because I have the sense the book should be somewhere in the doc, but would need to read some of the book or at least a summary, before I knew exactly where it should go. Feel free to take a try at it.

**Comment by solisruj** [comment]
Thanks, I will get on that as soon as a I have some free time.

Best,
Jose Solis

**Comment by hangtwenty** [comment]
No pressure! Only worthwhile if it’s an interesting subject to you anyways. :)

**Comment by solisruj** [comment]
Hey @hangtwenty  I finished the summary, and included the note in the "Assorted Opinions..." after "Ask for Peer Review" section. Please let me know if you have any other opportunities. :)

**Comment by hangtwenty** [comment]
@solisruj Thanks, want to submit your PR?

**Comment by solisruj** [comment]
@hangtwenty yes I would like that.

**Comment by hangtwenty** [comment]
@solisruj No problem, it is a little counter-intuitive. If you head to [this repository's Pull Request page](https://github.com/hangtwenty/dive-into-machine-learning/pulls) then you can submit the PR from your fork into this repository.

**Comment by solisruj** [comment]
@hangtwenty I created fork and made a pull request: https://github.com/solisruj/dive-into-machine-learning/pull/1 Would I just merge the pull request with yours then?

**Comment by hangtwenty** [comment]
@solisruj You must make the pull request target my repository rather than yours. Start a new pull request and select hangtwenty/master as the destination. Don’t worry about the old pull request, you can throw it away and make a new one easy. Branches and pull requests are “cheap”/disposable

**Comment by 97harsh** [comment]
Is the issue still open ?
I'd like to contribute

**Comment by UTpH** [comment]
Hi!
I would like to contribute to this if it is still open.

**Comment by VuProjects** [comment]
Yes! Please contribute anything as you please.

**Comment by UTpH** [comment]
@VuProjects So I brushed through the book and some reviews online and this is what I think the book would be useful for. It can be added in the Alternative ways to "Dive into Machine Learning" section.
"A quick read of the book is good for people with a business background who want to know what the various popular algorithms are.
It is also good for developers who are looking for Ruby based ML and/or want to see an OOP and test-driven approach to ML. This would possibly help with production quality ML and not required for personal learning and quick ML hacks."

**Comment by UTpH** [comment]
I am trying to push to a new branch but it says I do not have access. How do I go around that?

**Comment by hangtwenty** [comment]
Sorry for the confusion but upon review of the reviews of this book, I've decided it is not needed here for now.
