### ISSUE TITLE
Image linked from Photo Bucket not showing in readme

### ISSUE THREAD

**Issue by meetsha** [hangtwenty/dive-into-machine-learning#68]
Specifically in this section:
https://github.com/hangtwenty/dive-into-machine-learning#a-few-useful-things-to-know-about-machine-learning
The image at the end of this section (is from)/(hosted on) Photo Bucket and is not showing up. If possible we could use an alternative host for the image.

**Comment by hangtwenty** [comment]
Thank you for noticing this!

**Comment by hangtwenty** [comment]
[Per this guide](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/), I will just attaching the picture to this issue, then update the URL. 

However... While I made this image, I've lost it! 🤦‍♂️  I need to find it again, or remake it since it was rather simple. Tied up at the moment, but will do soon 😬

**Comment by hangtwenty** [comment]
Found it 🐶  ![diml impact diagram](https://user-images.githubusercontent.com/2420688/29441212-798d2bba-837e-11e7-90b1-21daaf8d7b73.png)

**Comment by hangtwenty** [comment]
Going to get the other images hosted here too while I'm at it...

**Comment by hangtwenty** [comment]
![That One Preview Gif about Visual Introduction](https://user-images.githubusercontent.com/2420688/29441234-a2028c98-837e-11e7-88f2-1ca5a94684f6.gif)

**Comment by hangtwenty** [comment]
![the trifecta with the danger zone](https://user-images.githubusercontent.com/2420688/29441268-f429d88c-837e-11e7-83ff-30874d832c89.png)

**Comment by hangtwenty** [comment]
![the "i'll wait" divider](https://user-images.githubusercontent.com/2420688/29441281-00eff0c4-837f-11e7-9666-d653a1cd2372.jpeg)

**Comment by hangtwenty** [comment]
Thanks again @meetsha for notifying me.
