### ISSUE TITLE
Include Orange in tools

### ISSUE THREAD

**Issue by michelemostarda** [hangtwenty/dive-into-machine-learning#72]
I suggest to add [Orange](https://orange.biolab.si) to the tools references.
Orange is an open source machine learning and data visualization for novice and expert. 
Provides an interactive data analysis workflows with a large toolbox.

**Comment by hangtwenty** [comment]
Thanks for the suggestion. As you may have noticed, this guide is not an exhaustive list to every lib; that already exists elsewhere.  Orange is already in the [Awesome Machine Learning](https://github.com/josephmisiti/awesome-machine-learning) list for example. That list is linked from this guide.
