### ISSUE TITLE
Add link to course Data 8: The Foundations of Data Science from UC Berkeley

### ISSUE THREAD

**Issue by ankitkul** [hangtwenty/dive-into-machine-learning#74]
I agree that hacking is the way you get started. But after going through the same process I struggled for some foundation later.

The [Data 8](http://data8.org/) course and the [inferential thinking](https://www.inferentialthinking.com/) textbook cover the foundations of data science. The course was designed for undergrads because students were struggling with concepts once taking advance topics at the grad level.

Also, the idea behind the course came from [Prof. Micheal Jordon](https://people.eecs.berkeley.edu/~jordan/) who is also linked to AMP Lab (the birth place for Spark).

PS: This is the only textbook with atleast a definition of Data Science compared to the Venn diagram which now has potentially 7-8 versions.

Wanted to confirm if you want to include this information:
- Atleast a link
- Or link with some description highlighting the importance of this course
- Using the definition of data science as mentioned in the text book (separate PR)

I can raise a PR based on your response.

**Comment by hangtwenty** [comment]
This looks good. Thanks for the context about this course. Seems like this makes sense to add somewhere in the Other Courses section, as another bullet. You have a few comments here so feel free to add all of that, nested list makes sense to me. Your call on where to put in the list; maybe between the 1st and 2nd items, or 2nd and 3rd?
