### ISSUE TITLE
Add Table of Contents at the Beginning of README

### ISSUE THREAD

**Issue by TheWindRider** [hangtwenty/dive-into-machine-learning#82]
I think it's better for README to have a table of contents, with clickables to jump directly to each of the high-level section headline. 
I feel it's **a good first task for me** as a rookie open-source contributor.  Kindly remind me of do's and dont's regarding making changes and pull requests.

**Comment by Jai-Z** [comment]
Hey there, Can I take this issue up?
Thanks

**Comment by TheWindRider** [comment]
@Jai-Z, I'm working on it, and my latest pull request is #84 .  I'll let you know if my pull request failed and let you take over this issue.

**Comment by Jai-Z** [comment]
Alright, thanks for letting me know!

**Comment by hangtwenty** [comment]
> Hello @TheWindRider , I appreciate your contribution. I agree with you in general that it's good to have a Table of Contents. 

> However this is just a special case a bit. I have thought this over a bit. I have set this up to pull people right in, without thinking about how far they have to go. The point is to "dive in." Adding a Table of Contents makes people think about where they are going and what they are getting into. We want to skip that and just get them going. 

> So I will decline this, but I appreciate your feedback and your effort.
