### ISSUE TITLE
Link to distill.pub

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#87]
https://distill.pub/about/

**Comment by sharad-vm** [comment]
I'd like to take this on. Can you provide some details on the issue please?

**Comment by hangtwenty** [comment]
Just review the existing document and find a reasonable place to add the link and a sentence or so 'pitching' it. Somewhere in 'Assorted Opinions and Other Resources' probably makes sense. Maybe the 'Deep Learning' subsection because distill.pub is mostly concerned with that subfield so far.

**Comment by jldohmann** [comment]
Hi, I submitted a pull request with this addition to the README.md file. It's my first pull request, so let me know if there's any comments/concerns.

**Comment by hangtwenty** [comment]
Thank you @jldohmann and @sharad-vm
