### ISSUE TITLE
Link to lore and a tutorial for it

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#92]
* https://github.com/instacart/lore/
* https://tech.instacart.com/how-to-build-a-deep-learning-model-in-15-minutes-a3684c6f71e

**Comment by ankitkul** [comment]
I was thinking of adding it into:

- "Finding Open-Source Libraries"
- Tutorial link in "Deep learning"

Let me know your thoughts.

**Comment by hangtwenty** [comment]
@ankitkul Yes that'd be perfect!

**Comment by hangtwenty** [comment]
@ankitkul If you're interested, #93 could be good to tackle at the same time.

**Comment by hangtwenty** [comment]
Ignore my last comment I was not up to date :)

**Comment by hangtwenty** [comment]
👍 Thanks again
