### ISSUE TITLE
Link to Google's new "crash course" using TensorFlow. (Deep Learning/ Other Guides)

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/dive-into-machine-learning#93]
https://developers.google.com/machine-learning/crash-course/

- [ ] add link in the Deep Learning section.
- [ ] add link in the Other Guides section.

**Comment by ankitkul** [comment]
@hangtwenty 
Raised PR #95.

**Comment by hangtwenty** [comment]
🙏
